version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest

    ports:
      - target: 3000
        published: 3000
        mode: host
      - target: 22
        published: 222
        mode: host

    volumes:
      - gitea_data:/data

    env_file:
      - .env


    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__APP_NAME=GITEA â€“ CI/CD PIPELINE TEST
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=smtp.gmail.com
      - GITEA__mailer__SMTP_PORT=465

volumes:
  gitea_data:
